{% set name = "ndindex" %}
{% set version = "1.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9cd9fa67044d12a8ed7b63ca7b38b45c51163962b67f133307a0cbe0721a953

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - ndindex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://quansight.github.io/ndindex/
  summary: A Python library for manipulating indices of ndarrays.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Quansight/ndindex

extra:
  recipe-maintainers:
    - asmeurer
