{% set name = "ndindex" %}
{% set version = "1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fc87ebc784605f01dd5367374cb40e8da8f2c30988968990066c5098a7eebe8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - ndindex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://quansight.github.io/ndindex/
  summary: A Python library for manipulating indices of ndarrays.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Quansight/ndindex

extra:
  recipe-maintainers:
    - asmeurer
