{% set name = "ndindex" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20e3a2f0a8ed4646abf0f13296aab0b5b9cc8c5bc182b71b5945e76eb6f558bb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools
    - cython
  run:
    - python

test:
  imports:
    - ndindex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://quansight.github.io/ndindex/
  summary: A Python library for manipulating indices of ndarrays.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Quansight/ndindex

extra:
  recipe-maintainers:
    - asmeurer
